### ISSUE TITLE
Adding links to projects that give kickstart of working with WP and Composer

### ISSUE THREAD

**Issue by ibes** [Rarst/composer-in-wp#4]
- WordPlate is a project that sets a strong foundation to have a kickstart with WP and Composer - it helped me to dive in this world: https://wordplate.github.io/docs/introduction

- Bedrock - haven't worked with it, but they also offer a small layer around WP and Composer - as far as I get: https://roots.io/bedrock/

**Comment by Rarst** [comment]
Thank you for suggestion! I am usually hesitant to outright recommend ready–made stacks as they can get very... opinionated. :) But I guess linking them up in resources is still worth it.
